name: Setup Faust
description: Install Faust to node_modules, so that it's cached by setup-node
inputs:
  version:
    description: 'Faust version'
    required: true
runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |-
      [[ -x node_modules/.faust/faust && -d node_modules/.faust/libraries ]] || (
        git clone --depth 1 https://github.com/grame-cncm/faust --branch ${{ inputs.version }} $RUNNER_TEMP/faust
        make -C $RUNNER_TEMP/faust compiler
        mkdir -p node_modules/.faust
        cp -r $RUNNER_TEMP/faust/{build/bin/faust,libraries} node_modules/.faust
      )
      echo $(pwd)/node_modules/.faust >> $GITHUB_PATH
