on:
  workflow_dispatch: {}

env:
  FAUST_VERSION: 2.33.1
  TAURI_CLI_VERSION: 34509028627aa44c02ec38bf6c45e797c8ccfc69

jobs:
  main:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: |-
          Invoke-WebRequest https://github.com/grame-cncm/faust/releases/download/${{ env.FAUST_VERSION }}/Faust-${{ env.FAUST_VERSION }}-win64.exe -OutFile ${{ runner.temp }}/faust.exe
          echo ${{ runner.temp }} | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: cargo install --git https://github.com/tauri-apps/tauri --rev ${{ env.TAURI_CLI_VERSION }} tauri-cli
      - run: cargo tauri build
      - run: netlify deploy --alias windows --dir target/release/bundle/msi
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
